//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ticketID { get; set; }
        public Nullable<int> userID { get; set; }
        public string date { get; set; }
        public string description { get; set; }
        public int status { get; set; }
        public int type { get; set; }
    
        public virtual user user { get; set; }
    }
}
